"""Controls editor tab for the project GUI.

Reads the project's ``configs/marginals_groups.yaml`` plus the package
config CSVs, lets the user pick a geography and importance for each
marginal group and for individual total variables, and writes a
populationsim-style ``configs/controls.csv`` to the project directory.

Seed expressions for aggregated bins are generated by OR-combining
the source row expressions from ``marginals_expressions.csv``.
"""

from collections import OrderedDict
from pathlib import Path

import pandas as pd
import streamlit as st
import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_PKG_DIR = Path(__file__).resolve().parent.parent
_ACS_MARG_PATH = _PKG_DIR / "configs" / "acs_2024" / "marginals_expressions.csv"
_DEC_MARG_PATH = _PKG_DIR / "configs" / "dec_2020" / "block_marginals_expressions.csv"
_ACS_TOTALS_PATH = _PKG_DIR / "configs" / "acs_2024" / "total_variables.csv"
_DEC_TOTALS_PATH = _PKG_DIR / "configs" / "dec_2020" / "total_variables.csv"

# Geography option presets
_GEO_ACS = ["tract_id", "region"]
_GEO_DEC = ["block_id", "tract_id", "region"]


# ---------------------------------------------------------------------------
# Loading helpers
# ---------------------------------------------------------------------------


def load_marginals_groups(project_dir: Path) -> "OrderedDict[str, list[tuple[str, list[str]]]]":
    """Read the project's ``marginals_groups.yaml``.

    Returns ``{group: [(bin_name, [component_name, ...]), ...]}``.
    Missing or empty file → empty OrderedDict.
    """
    yaml_path = project_dir / "configs" / "marginals_groups.yaml"
    if not yaml_path.exists():
        return OrderedDict()
    raw = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}
    out: "OrderedDict[str, list[tuple[str, list[str]]]]" = OrderedDict()
    for group, bins in raw.items():
        bin_list: list[tuple[str, list[str]]] = []
        if bins is None:
            continue
        for item in bins:
            if isinstance(item, dict):
                for k, v in item.items():
                    components = [str(s) for s in (v if isinstance(v, list) else [v])]
                    bin_list.append((str(k), components))
        out[group] = bin_list
    return out


def load_acs_marginals_expr() -> dict[tuple[str, str], str]:
    df = pd.read_csv(_ACS_MARG_PATH, dtype=str).fillna("")
    return {
        (row["group"], row["name"]): row.get("seed_expression", "")
        for _, row in df.iterrows()
    }


def load_dec_block_marginals_expr() -> dict[tuple[str, str], str]:
    df = pd.read_csv(_DEC_MARG_PATH, dtype=str).fillna("")
    if "seed_expression" not in df.columns:
        return {}
    return {
        (row["group"], row["name"]): row["seed_expression"]
        for _, row in df.iterrows()
    }


def load_total_variables() -> list[tuple[str, str, str]]:
    """Return list of ``(name, source, seed_expression)`` for all totals."""
    out: list[tuple[str, str, str]] = []
    for path, source in [(_ACS_TOTALS_PATH, "acs"), (_DEC_TOTALS_PATH, "dec")]:
        if not path.exists():
            continue
        df = pd.read_csv(path, dtype=str).fillna("")
        expr_col = "seed_expression" if "seed_expression" in df.columns else None
        for _, row in df.iterrows():
            expr = row[expr_col] if expr_col else ""
            out.append((row["name"], source, expr))
    return out


# ---------------------------------------------------------------------------
# Expression utilities
# ---------------------------------------------------------------------------


def combine_seed_expressions(exprs: list[str]) -> str:
    cleaned = [e.strip() for e in exprs if e and str(e).strip()]
    if not cleaned:
        return ""
    if len(cleaned) == 1:
        return cleaned[0]
    return " | ".join(f"({e})" for e in cleaned)


def seed_table_from_expr(expr: str) -> str:
    if not expr:
        return ""
    token = expr.strip().lstrip("(").split(".", 1)[0].strip()
    return token


# ---------------------------------------------------------------------------
# Group → bins mapping (yaml + auto-included tenure)
# ---------------------------------------------------------------------------


def get_group_bins(project_dir: Path) -> "OrderedDict[str, list[tuple[str, list[str], str]]]":
    """Return ``{group: [(bin_name, [components], source), ...]}`` where
    ``source`` is ``'acs'`` or ``'dec'``. Groups present in the DEC block
    marginals CSV but absent from the yaml (e.g. ``tenure``) are appended 1:1.
    """
    yaml_groups = load_marginals_groups(project_dir)
    dec_expr = load_dec_block_marginals_expr()
    dec_group_names: "OrderedDict[str, list[str]]" = OrderedDict()
    for group, name in dec_expr.keys():
        dec_group_names.setdefault(group, []).append(name)

    out: "OrderedDict[str, list[tuple[str, list[str], str]]]" = OrderedDict()
    for group, bins in yaml_groups.items():
        source = "dec" if group in dec_group_names else "acs"
        out[group] = [(name, comps, source) for name, comps in bins]

    for group, names in dec_group_names.items():
        if group not in out:
            out[group] = [(name, [name], "dec") for name in names]
    return out


def geographies_for_group(group: str, source: str = "acs") -> list[str]:
    return _GEO_DEC if source == "dec" else _GEO_ACS


def geographies_for_total(source: str) -> list[str]:
    return _GEO_DEC if source == "dec" else _GEO_ACS


# ---------------------------------------------------------------------------
# controls.csv builder
# ---------------------------------------------------------------------------


_AUTO_ROWS = [
    {
        "target": "num_units",
        "geography": "block_id",
        "seed_table": "households",
        "importance": 1_000_000_000,
        "control_field": "num_units",
        "expression": "(households.wgtp > 0) & (households.wgtp < np.inf)",
    },
    {
        "target": "num_persons",
        "geography": "region",
        "seed_table": "persons",
        "importance": 10_000,
        "control_field": "num_persons",
        "expression": "persons.hh_id > 0",
    },
]


def build_controls_rows(
    group_bins: "OrderedDict[str, list[tuple[str, list[str], str]]]",
    group_choices: dict[str, dict],
    individual_choices: list[dict],
    acs_expr: dict[tuple[str, str], str],
    dec_expr: dict[tuple[str, str], str],
) -> tuple[pd.DataFrame, list[str]]:
    """Build the final controls DataFrame and return ``(df, warnings)``."""
    rows = list(_AUTO_ROWS)
    warnings: list[str] = []

    for group, bins in group_bins.items():
        if group not in group_choices:
            continue
        geog = group_choices[group]["geography"]
        importance = int(group_choices[group]["importance"])
        for bin_name, components, src in bins:
            expr_lookup = dec_expr if src == "dec" else acs_expr
            comp_exprs = [expr_lookup.get((group, c), "") for c in components]
            combined = combine_seed_expressions(comp_exprs)
            if not combined:
                warnings.append(
                    f"Skipped {group}_{bin_name}: no seed_expression found for components {components}."
                )
                continue
            target = f"{group}_{bin_name}"
            rows.append({
                "target": target,
                "geography": geog,
                "seed_table": seed_table_from_expr(combined),
                "importance": importance,
                "control_field": target,
                "expression": combined,
            })

    for choice in individual_choices:
        expr = (choice.get("expression") or "").strip()
        if not expr:
            warnings.append(
                f"Skipped individual variable '{choice['name']} ({choice['source']})': no seed_expression defined."
            )
            continue
        rows.append({
            "target": choice["name"],
            "geography": choice["geography"],
            "seed_table": seed_table_from_expr(expr),
            "importance": int(choice["importance"]),
            "control_field": choice["name"],
            "expression": expr,
        })

    df = pd.DataFrame(rows, columns=[
        "target", "geography", "seed_table", "importance", "control_field", "expression",
    ])
    return df, warnings


# ---------------------------------------------------------------------------
# Streamlit UI
# ---------------------------------------------------------------------------


def _slider_importance(key: str, default: int = 1000) -> int:
    # Only supply a default value when the key isn't already in session state,
    # otherwise Streamlit warns about setting value both ways.
    kwargs = {} if key in st.session_state else {"value": int(default)}
    return st.slider(
        "Importance",
        min_value=0,
        max_value=10000,
        step=100,
        key=key,
        **kwargs,
    )


# ---------------------------------------------------------------------------
# Load existing controls.csv into session state
# ---------------------------------------------------------------------------


_AUTO_TARGETS = {row["target"] for row in _AUTO_ROWS}


def _match_group(target: str, group_names: list[str]) -> str | None:
    """Return the longest group name that is a ``{group}_`` prefix of target."""
    candidates = [g for g in group_names if target.startswith(f"{g}_")]
    if not candidates:
        return None
    return max(candidates, key=len)


def _auto_load_controls(
    controls_path: Path,
    group_bins: "OrderedDict[str, list[tuple[str, list[str], str]]]",
    totals: list[tuple[str, str, str]],
) -> None:
    """Populate st.session_state from an existing controls.csv (once)."""
    if st.session_state.get("controls__loaded"):
        return
    st.session_state["controls__loaded"] = True
    if not controls_path.exists():
        return

    try:
        df = pd.read_csv(controls_path)
    except Exception:
        return
    required = {"target", "geography", "importance"}
    if not required.issubset(df.columns):
        return

    group_names = list(group_bins.keys())
    totals_by_name = {name: source for name, source, _ in totals}
    individual_selected: list[str] = []
    seen_individuals: set[str] = set()

    for _, row in df.iterrows():
        target = str(row["target"])
        if target in _AUTO_TARGETS:
            continue
        try:
            importance = int(row["importance"])
        except (TypeError, ValueError):
            continue
        geography = str(row["geography"])

        group = _match_group(target, group_names)
        if group is not None:
            # Only set once per group (first matching row wins)
            geo_key = f"ctrl_geog__{group}"
            imp_key = f"ctrl_imp__{group}"
            st.session_state.setdefault(geo_key, geography)
            st.session_state.setdefault(imp_key, importance)
            continue

        # Individual variable?
        if target in totals_by_name:
            source = totals_by_name[target]
            label = f"{target} ({source})"
            if target not in seen_individuals:
                seen_individuals.add(target)
                individual_selected.append(label)
            geo_key = f"ctrl_var_geog__{source}__{target}"
            imp_key = f"ctrl_var_imp__{source}__{target}"
            st.session_state.setdefault(geo_key, geography)
            st.session_state.setdefault(imp_key, importance)

    if individual_selected and "ctrl_individual_selected" not in st.session_state:
        st.session_state["ctrl_individual_selected"] = individual_selected


def render(project_dir: Path):
    """Render the Controls editor tab.

    Parameters
    ----------
    project_dir : Path
        Root of the example project. The output is written to
        ``project_dir/popsim_configs/controls.csv``.
    """
    out_path = project_dir / "popsim_configs" / "controls.csv"

    group_bins = get_group_bins(project_dir)
    if not group_bins:
        st.warning(
            "No marginal groups found. Configure them in the 'Marginals Groups' tab first."
        )
        return

    acs_expr = load_acs_marginals_expr()
    dec_expr = load_dec_block_marginals_expr()
    totals = load_total_variables()

    _auto_load_controls(out_path, group_bins, totals)

    st.subheader("Marginal Groups")
    st.caption(
        "Pick a geography and importance for each group. All bins within a "
        "group share the same geography and importance."
    )

    group_choices: dict[str, dict] = {}
    for group, bins in group_bins.items():
        with st.expander(f"**{group}** ({len(bins)} bin{'s' if len(bins) != 1 else ''})", expanded=True):
            preview = ", ".join(f"`{b[0]}`" for b in bins)
            st.caption(f"Bins: {preview}")
            geo_options = geographies_for_group(group, bins[0][2] if bins else "acs")
            geo_key = f"ctrl_geog__{group}"
            imp_key = f"ctrl_imp__{group}"
            geo_kwargs = {} if geo_key in st.session_state else {"index": 0}
            geog = st.selectbox(
                "Geography",
                options=geo_options,
                key=geo_key,
                **geo_kwargs,
            )
            importance = _slider_importance(imp_key)
            group_choices[group] = {"geography": geog, "importance": importance}

    st.subheader("Individual Variables")
    st.caption(
        "Optional. Add one or more total variables from the package configs."
    )

    label_to_total = {f"{name} ({source})": (name, source, expr) for name, source, expr in totals}
    selected_labels = st.multiselect(
        "Variables",
        options=list(label_to_total.keys()),
        key="ctrl_individual_selected",
    )

    individual_choices: list[dict] = []
    for label in selected_labels:
        name, source, expr = label_to_total[label]
        with st.expander(f"**{label}**", expanded=True):
            if not expr:
                st.warning(
                    "No seed_expression defined for this variable in total_variables.csv. "
                    "It will be skipped on save."
                )
            geo_options = geographies_for_total(source)
            geo_key = f"ctrl_var_geog__{source}__{name}"
            imp_key = f"ctrl_var_imp__{source}__{name}"
            geo_kwargs = {} if geo_key in st.session_state else {"index": 0}
            geog = st.selectbox(
                "Geography",
                options=geo_options,
                key=geo_key,
                **geo_kwargs,
            )
            importance = _slider_importance(imp_key)
            individual_choices.append({
                "name": name,
                "source": source,
                "expression": expr,
                "geography": geog,
                "importance": importance,
            })

    st.divider()
    if st.button("Save controls.csv", type="primary"):
        df, warnings = build_controls_rows(
            group_bins, group_choices, individual_choices, acs_expr, dec_expr
        )
        out_path.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(out_path, index=False)
        st.success(f"Wrote {len(df)} rows to {out_path}")
        for w in warnings:
            st.warning(w)
        with st.expander("Preview", expanded=True):
            st.dataframe(df, use_container_width=True)
